blog_project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts', views.post_list, name='postlist'),
    path('posts/search', views.post_search, name='postsearch'),
    path('add-post', views.add_post, name='addpost'),
    path('post-edit/<int:id>', views.post_edit, name='postedit'),
    path('post-delete/<int:id>', views.post_delete, name='postdelete'),
    path('post-operations', views.post_operations, name='postoperations'),
    path('<slug:slug>', views.post_details, name='postdetails'),
    path('posts/<slug:slug>', views.get_posts_by_category, name='getpostsbycategory'),
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_project/blog/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, editable=False)
    is_active = models.BooleanField(default=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)  
        
    def __str__(self):
        return self.name  
    
class Post(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=50, default="")
    slug = models.SlugField(editable=True, blank=True, null=False, unique=True)#blank formda slug bilgisi girmek zorunda kalmayalım diye
    content = models.TextField()
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, default=1, on_delete=models.CASCADE, related_name="posts")
    published_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    image = models.ImageField(null=True, upload_to='posts/images/')
    is_active = models.BooleanField(default=1)
    
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()
          
    def save(self, *args, **kwargs):
        
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)    
    
    def __str__(self):
        return self.title
    

blog_project/blog/forms.py
from django import forms
from blog.models import Post

'''class PostCreateForm(forms.Form):
    title = forms.CharField(label='Post Title',
                            max_length=5,
                            error_messages={'required':'Please Enter A Value', 'max_length':'max 5'},
                            widget=forms.TextInput(attrs={'class':'form-control'})
                            )#required zaten varsayilan olarak true
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
    image = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))'''
    

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content','category','author','image','is_active')
        labels = {'title':'Title',
                  'content':'Content',
                  'category':'Category',
                   'author':'Author',
                  'image':'Image',
                  'is_active':'Active',
                  }
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class': 'form-select'}),
            'author':forms.Select(attrs={'class':'form-select'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'is_active':forms.CheckboxInput(attrs={'class':'form-check'})
        }
        error_messages={
            'title':{
                'required':'Please enter title',
                'max_length':'Please enter max 50 char'
            },
            'content':{
                'required':'please enter content'
            }
            
        }
        
        
class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content','category','author','image','is_active')
        labels = {'title':'Title',
                  'content':'Content',
                  'category':'Category',
                  'author':'Author',
                  'image':'Image',
                  'is_active':'Active',
                  }
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class': 'form-select'}),
            'author':forms.Select(attrs={'class':'form-select'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'is_active':forms.CheckboxInput(attrs={'class':'form-check'})
        }
        error_messages={
            'title':{
                'required':'Please enter title',
                'max_length':'Please enter max 50 char'
            },
            'content':{
                'required':'please enter content'
            }
            
        }

blog_project/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.forms import CreatePostForm, EditPostForm
from .models import Post, Category, User
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, user_passes_test
# Create your views here.


def post_list(request):
    posts = Post.objects.all().order_by('-published_date')
    categories = Category.objects.all()
    
    paginator = Paginator(posts, 9)
    page = request.GET.get('page',1) #sayfadan 'page' değeri geliyorsa al, gelmiyorsa 1 al. bu satır şuan hangi sayfada olduğumuzu alır.
    page_obj = paginator.get_page(page)
    
    print(page_obj.paginator.num_pages) #postlar toplam kaç sayfaya dağıtıldı?
    print(page_obj.paginator.count) #toplam kaç tane post var?
    
    return render(request, 'blog/post_list.html', {'page_obj':page_obj, 'categories':categories})


def post_details(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'blog/post_details.html', {'post':post})


def home(request):
    return render(request, 'blog/index.html')


def get_posts_by_category(request, slug):
    categories = Category.objects.all()
    posts = Post.objects.filter(category__slug = slug).order_by('-published_date')
    
    paginator = Paginator(posts, 9)
    page = request.GET.get('page',1) #sayfadan 'page' değeri geliyorsa al, gelmiyorsa 1 al. bu satır şuan hangi sayfada olduğumuzu alır.
    page_obj = paginator.get_page(page)
    
    
    return render(request, 'blog/post_list.html', context={'categories':categories, 'page_obj':page_obj, 'selected_category':slug})


def post_search(request):
    if 'q' in request.GET and request.GET['q'] != '':
        q = request.GET['q']
        categories = Category.objects.all()
        posts = Post.objects.filter(is_active=True, title__contains=q).order_by('-published_date')
    else:
        return redirect("/posts")    
    
    return render(request, 'blog/search.html', context={'categories':categories, 'posts':posts})


#kullanıcı admin ise ve login durumundaysa true döndürür ve method çalışır, admin değilse veya login değilse false döndürür ve method çalışmaz
def is_admin(user): 
    if user.is_authenticated and user.is_superuser:
        return True
    else:
        return False
    

@user_passes_test(is_admin) # parametre true ise method çalışır, değilse çalışmaz ve login sayfasına yönlendirir.
def add_post(request):   
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/posts')
    else:
        form = CreatePostForm()
    return render(request, 'blog/add_post.html', context={'form':form})



@user_passes_test(is_admin)
def post_operations(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_op.html', {'posts':posts})



def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    
    if request.method == 'POST':
        form = EditPostForm(request.POST, request.FILES, instance=post)
        form.save()
        return redirect('/post-operations')
    else:
        form = EditPostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form':form, 'id':id, 'img':post.image.url})



def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        post.delete()
        return redirect('/post-operations')
    
    return render(request, 'blog/post_delete.html', {'post':post})

blog_project/blog/templates/blog/add_post.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}Posts{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-12">

                <form action="{% url 'blog:addpost' %}" method="POST" novalidate  enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="mb-3 {% if field.errors %}invalid{% endif %}">
                            {% if field.errors %}
                            <div class="alert alert-danger">{{ field.errors }}</div>
                            {% endif %}
                            <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-dark">Submit</button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

blog_project/blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block css %}
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container-fluid p-0">
        <div class="myclass">
            <div class="container text-center">
                <h1>Welcome To My Blog</h1>
            </div>
        </div>
    </div>
{% endblock %}

blog_project/blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block css %}
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container-fluid p-0">
        <div class="myclass">
            <div class="container text-center">
                <h1 style="user-select: none;">Django Blog Project</h1>
            </div>
        </div>
    </div>
{% endblock %}

blog_project/blog/templates/blog/post_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts{% endblock%}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <p>
                    <strong>{{ post.title }}, Are you sure you want to delete this post?</strong>
                    <form action="{% url 'blog:postdelete' post.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger"  style="width: 75px;">Delete</button>
                        <a href="{% url 'blog:postoperations' %}" class="btn btn-dark" style="width: 75px;">No</a>
                    </form>

                </p>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
{% endblock %}

blog_project/blog/templates/blog/post_details.html
{% extends 'base.html' %}

{% block title %}Details{% endblock%}

{% block content %}
    
<div class="container mt-4">
    <div class="row">
        <div class="col-2 text-end">
            <button type="button" class="btn-close" aria-label="Close" onclick="history.back()"></button>
        </div>
        <div class="col-8">
            <div class="card mb-1">
                <img src="{{ post.image.url }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|safe}}</p>
                    <p class="card-text"><small class="text-body-secondary">Published on: {{ post.published_date }}</small></p>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>

{% endblock %}

blog_project/blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}Posts{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-12 ">

                <div class="row">
                    <div class="col-4 mt-4"><button type="button" class="btn-close" aria-label="Close" onclick="history.back()"></button></div>
                    <div class="col-4"><img src="{{ img }}" class="img-fluid rounded" ></div>
                    <div class="col-4"></div>
                </div>

                <form action="{% url 'blog:postedit' id %}" method="POST" novalidate enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="mb-3 {% if field.errors %}invalid{% endif %}">
                            {% if field.errors %}
                            <div class="alert alert-danger">{{ field.errors }}</div>
                            {% endif %}
                            <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-dark">Submit</button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

blog_project/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts{% endblock%}


{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-sm-3 mb-3">
                <div class="list-group">
                    <a href="/posts" class="list-group-item list-group-item-action {% if not selected_category %}active{% endif %}">All Posts</a>
                    {% for category in categories %}   
                        <a href="{% url 'blog:getpostsbycategory' category.slug %}" class="list-group-item list-group-item-action 
                        {% if category.slug == selected_category %}active{% endif %}">{{category.name}}</a>  
                    {% endfor %}
                </div>
            </div>

            <div class="col-sm-9">
                {% if page_obj.object_list|length == 0 %}
                    <div class="alert alert-warning">
                        No Post Founded
                    </div>
                {% endif %}

                
                <div class="row">
                    {% for post in page_obj.object_list %}
                        {% if post.is_active %}
                            <div class="col-sm-4 mb-5">
                                <div class="card" style="width: 25rem;">
                                    <img src="{{ post.image.url }}" class="card-img-top" height="220">
                                    <div class="card-body">
                                        <h5 class="card-title">
                                            <a href="{% url 'blog:postdetails' post.slug %}" class="text-decoration-none">{{ post.title }}</a>
                                        </h5>
                                        <p class="card-text">{{ post.subtitle }}</p>
                                        <p>Author: {{ post.author }}</p>
                                        <p class="fw-light">Published on: {{ post.published_date }}</p>
                                        <a href="{% url 'blog:postdetails' post.slug %}" class="btn btn-dark">Details</a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}    
                    {% endfor %}
                </div>

                
                {% if page_obj.paginator.num_pages > 1 %}
                    <nav aria-label="Page navigation example" >
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                            {% endif %}

                            {% for page_num in page_obj.paginator.page_range %}
                                {% if page_obj.number == page_num %}
                                    <li class="page-item disabled"><a class="page-link" href="#">{{ page_num }}</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>    
                                {% endif %}    
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                            {% endif %}
                            
                        </ul>
                    </nav>
                {% endif %}    
            </div>

        </div>
    </div>
{% endblock %}

blog_project/blog/templates/blog/post_op.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts{% endblock%}

{% block css %}
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" style="width:275px;"></th>
                            <th scope="col">Title</th>
                            <th scope="col">Content</th>
                            <th scope="col">Author</th>
                            <th scope="col">Published_date</th>
                            <th scope="col">Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <td>
                                    <img src="{{ post.image.url }}" class="img-fluid rounded" >
                                </td>
                                <td>{{ post.title }}</td>
                                <td>{{ post.subtitle }}</td>
                                <td>{{ post.author }}</td>
                                <td>{{ post.published_date }}</td>
                                <td>
                                    <a href="{% url 'blog:postedit' post.id %}" class="btn btn-dark btn-sm" style="width: 70px;">Update</a>
                                    <a href="{% url 'blog:postdelete' post.id %}" class="btn btn-danger btn-sm" style="width: 70px;">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}

blog_project/blog/templates/blog/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts{% endblock%}


{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-sm-3 mb-3">
                <div class="list-group">
                    <a href="/posts" class="list-group-item list-group-item-action {% if not selected_category %}active{% endif %}">All Posts</a>
                    {% for category in categories %}   
                        <a href="{% url 'blog:getpostsbycategory' category.slug %}" class="list-group-item list-group-item-action 
                        {% if category.slug == selected_category %}active{% endif %}">{{category.name}}</a>  
                    {% endfor %}
                </div>
            </div>

            <div class="col-sm-9">
                {% if posts|length == 0 %}
                    <div class="alert alert-warning">
                        No Post Founded
                    </div>
                {% endif %}

                <div class="row">
                    {% for post in posts %}
                        {% if post.is_active %}
                            <div class="col-sm-4 mb-5">
                                <div class="card" style="width: 25rem;">
                                    <img src="{{ post.image.url }}" class="card-img-top" height="220">
                                    <div class="card-body">
                                        <h5 class="card-title">
                                            <a href="{% url 'blog:postdetails' post.slug %}" class="text-decoration-none">{{ post.title }}</a>
                                        </h5>
                                        <p class="card-text">{{ post.subtitle}}</p>
                                        <p>Author: {{ post.author }}</p>
                                        <p class="fw-light">Published on: {{ post.published_date }}</p>
                                        <a href="{% url 'blog:postdetails' post.slug %}" class="btn btn-dark">Details</a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}    
                    {% endfor %}
                </div>

            </div>

        </div>
    </div>
{% endblock %}