blog_project/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.login_user, name='loginuser'),
    path('logout', views.logout_user, name='logoutuser'),
    path('register', views.register_user, name='registeruser'),
]

blog_project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts', views.post_list, name='postlist'),
    path('posts/search', views.post_search, name='postsearch'),
    path('add-post', views.add_post, name='addpost'),
    path('post-edit/<int:id>', views.post_edit, name='postedit'),
    path('post-delete/<int:id>', views.post_delete, name='postdelete'),
    path('post-operations', views.post_operations, name='postoperations'),
    path('<slug:slug>', views.post_details, name='postdetails'),
    path('posts/<slug:slug>', views.get_posts_by_category, name='getpostsbycategory'),
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_project/templates/includes/_messages.html
{% if messages %}
    <div class="container-fluid p-0 m-0">
        {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }} alert-dismissible fade show text-center mb-0" {% endif %}>
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

blog_project/templates/includes/_nav.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light fixed-navbar-height" style="background-color: #DFDFE3;">
    <div class="container-fluid">
        <a href="/"><img src="{% static 'img/blog.png' %}" style="margin-right: 15px;" width="30px"></a>
        <a class="navbar-brand me-3 mt-2 h1" href="/">Blog App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbar">

            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active mt-2" aria-current="page" href="{% url 'blog:postlist' %}">Posts</a>
                </li>
                {% if user.is_superuser %}
                
                <li class="nav-item">
                    <a class="nav-link active mt-2" href="{% url 'blog:addpost' %}">Admin Add Post</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link active mt-2" href="{% url 'blog:postoperations' %}">Admin Posts</a>
                </li>
                
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mt-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                    </a>
                    <ul class="dropdown-menu py-2">
                        <li><a class="dropdown-item dropdown-item-size" href="#">About</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item dropdown-item-size" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item dropdown-item-size" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav me-2 ">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="#">{{user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:logoutuser' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:registeruser' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:loginuser' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
            {% if page_obj is not None or posts is not None%}
            <form class="d-flex" action="{% url 'blog:postsearch' %}" role="search">
                <input class="form-control me-1 mt-3" type="text" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-dark mt-3" type="submit">Search</button>
            </form>
            {% endif %}
        </div>
    </div>  
</nav>